backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "writings"
    label: "Writings"
    folder: "src/content/writings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "notes"
    label: "Notes"
    folder: "src/content/notes"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - { label: "Body", name: "body", widget: "text" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - { label: "Intro", name: "body", widget: "markdown" }
